on: [push]

jobs:
  test-linux:
    runs-on: ubuntu-20.04
    name: Test Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        id: setup
        with:
          version: '9.17.0'

  test-linux-container:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/dotnet/sdk:8.0
    name: Test Linux Container
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        id: setup
        with:
          version: '9.17.0'

  test-linux-packages:
    runs-on: ubuntu-20.04
    name: Test Linux (Packages)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        id: setup
        with:
          version: '9.17.0'
          packages: 'Demonstration,PackagePublish:rc,TUI:any'

  test-win:
    runs-on: windows-2022
    name: Test Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        id: setup
        with:
          version: '9.17.0'    

  test-macos:
    runs-on: macos-14
    name: Test MacOS
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        id: setup
        with:
          version: '9.17.0'

  test-macos-packages:
    runs-on: macos-14
    name: Test MacOS (Packages)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        id: setup
        with:
          version: '9.19.1'
          packages: 'Runner,TUI:any'

  test-user-token:
    runs-on: ubuntu-20.04
    name: Test Installing Private Packages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        id: setup
        with:
          version: '9.22.0-beta.1'
          packages: 'Sign,Dotfuscator,DocumentationGeneration'
          additional-repository: 'https://test-automation.pw.keysight.com/api/packages'
          token: ${{ secrets.OPENTAP_USERTOKEN }}

  test-additional-user-token:
    runs-on: ubuntu-20.04
    name: Test Installing Private Packages 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        id: setup
        with:
          version: 9.23.0
          packages: 'DocumentationGeneration:1.0.2'
          additional-repository: 'https://test-automation.pw.keysight.com/api/packages'
          additional-repository-token: '${{ secrets.KS8500_REPO_TOKEN }}'
      - run: tap package list --version any | grep '^ESD'

  test-packages-with-spaces:
    runs-on: ubuntu-20.04
    name: Test Packages With Spaces In Names
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        id: setup
        with:
          version: '9.21.0'
          packages: 'Editor X:1.5.0-beta.41+2c6d736c,NATS Server,CSV'
