on: [push]

jobs:
  test-linux:
    runs-on: ubuntu-20.04
    name: Test Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./ # Uses an action in the root directory
        id: setup
        with:
          version: '9.17.0'

  test-win:
    runs-on: windows-2022
    name: Test Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./ # Uses an action in the root directory
        id: setup
        with:
          version: '9.17.0'    